### ISSUE TITLE
Does it support injection mode ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [1999AZZAR/use-RTL8188FTV-on-linux#1]
or VIF ( virtual interfaces ? ) 

You can check using this command 

`iw list | grep "Supported interface modes" -A 8 and you should see in the output AP/VLAN`

can you report quickly pls , i am about to buy a one tomorrow : (

**Comment by 1999AZZAR** [comment]
![image](https://user-images.githubusercontent.com/48999412/223339465-ba3c791a-2378-4528-9143-35a9ffa8a13f.png)
i'am not sure but this is what come from the command

**Comment by minanagehsalalma** [comment]
> i'am not sure but this is what come from the command

@1999AZZAR it doesn't even support monitor mode 😵‍💫😵‍💫

How?  Most sources say that it does

**Comment by minanagehsalalma** [comment]
@1999AZZAR what does
airmon-ng start wlan0 show?
