### ISSUE TITLE
sudo add-apt-repository: command not found.

### ISSUE THREAD

**Issue by Savage-Army** [1999AZZAR/use-RTL8188FTV-on-linux#11]
While doing sudo add-apt-repository ppa:kelebek333/kablosuz in the terminal got error.

![image](https://github.com/1999AZZAR/use-RTL8188FTV-on-linux/assets/116685576/2472d757-8ce6-4647-bd90-593fd8c8565f)

**Comment by 1999AZZAR** [comment]
i don't know about your system, but it still work just fine for me (kubuntu with 6.8.1-060801 kernel).
![Screenshot_20240330_190947](https://github.com/1999AZZAR/use-RTL8188FTV-on-linux/assets/48999412/371d7191-3470-4714-9356-f37a93b07dcc)
