### ISSUE TITLE
error in PRETTY_NAME="Parrot Security 6.0 (lorikeet)" NAME="Parrot Security" VERSION_ID="6.0" VERSION="6.0 (lorikeet)" VERSION_CODENAME=lory ID=debian HOME_URL="https://www.parrotsec.org/" SUPPORT_URL="https://www.parrotsec.org/community/" BUG_REPORT_URL="https://gitlab.com/parrotsec/"

### ISSUE THREAD

**Issue by adarshthakur14777** [1999AZZAR/use-RTL8188FTV-on-linux#12]
sudo apt update
Hit:1 https://mirrors.nxtgen.com/parrot-mirror lory InRelease                           
Hit:2 https://deb.parrot.sh/parrot lory InRelease                                       
Hit:3 https://deb.parrot.sh/direct/parrot lory-security InRelease                       
Ign:4 http://ppa.launchpad.net/kelebek333/kablosuz lory InRelease                      
Ign:5 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory InRelease               
Hit:6 http://dl.google.com/linux/earth/deb stable InRelease
Err:7 http://ppa.launchpad.net/kelebek333/kablosuz lory Release
  404  Not Found [IP: 2620:2d:4000:1::81 80]
Ign:8 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory Release
Ign:9 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all Packages
Ign:10 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 Packages
Ign:11 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en
Ign:12 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 DEP-11 Metadata
Ign:9 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all Packages
Ign:10 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 Packages
Ign:11 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en
Ign:12 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 DEP-11 Metadata
Ign:9 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all Packages
Ign:10 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 Packages
Ign:11 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en
Ign:12 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 DEP-11 Metadata
Ign:9 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all Packages
Ign:10 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 Packages
Ign:11 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en
Ign:12 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 DEP-11 Metadata
Ign:9 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all Packages
Ign:10 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 Packages
Ign:11 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en
Ign:12 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 DEP-11 Metadata
Ign:9 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all Packages
Ign:10 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 Packages
Ign:11 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en
Ign:12 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 DEP-11 Metadata
Ign:9 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all Packages
Err:10 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 Packages
  404  Not Found [IP: 2620:2d:4000:1::81 80]
Ign:11 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en
Ign:12 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main Translation-en_IN
Ign:13 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main all DEP-11 Metadata
Ign:14 http://ppa.launchpad.net/kelebek333/kablosuz/ubuntu lory/main amd64 DEP-11 Metadata
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/kelebek333/kablosuz lory Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by 1999AZZAR** [comment]
Basically the error u are encounter are due to the distro u are currently use (parrot os)
