### ISSUE TITLE
Repository command not working on KALI LINUX NEED HELP!!!

### ISSUE THREAD

**Issue by Alif08bd** [1999AZZAR/use-RTL8188FTV-on-linux#3]
![repository](https://github.com/1999AZZAR/use-RTL8188FTV-on-linux/assets/81166030/f591cd04-ff60-41ff-99ac-76ce7944b661)

hello, I am on kali linux the command "sudo add-apt-repository ppa:kelebek333/kablosuz" Not Working I have given a screenshot. Please Help me, Thanks.

**Comment by 1999AZZAR** [comment]
I think this can help you.

https://www.blackmoreops.com/2014/02/21/kali-linux-add-ppa-repository-add-apt-repository/
