### ISSUE TITLE
How do I uninstall this driver program?

### ISSUE THREAD

**Issue by HuXinjing** [1999AZZAR/use-RTL8188FTV-on-linux#5]
Hi, bro. I found this driver program can't work well with my device, is there any flow to uninstall it? When I use other diver-install program it show me some error message like "libkmod:ERROR ../libkmod/libkmod-config.c:712 kmod_config_parse:/etc/modprobe.d/rtl8188fu.config line 1:ignoring bad line starting with options modprobe:FATAL:module rtl8188fu not found", which bother me a lot.

**Comment by 1999AZZAR** [comment]
oh hi there, To uninstall the driver program, you can try the following steps:

Open a terminal window.
Run the following command to find the location of the driver program:
```text
sudo find / -name rtl8188fu.ko
```
This will list the location of the driver program, if it is still installed on the system.

If the driver program is found, run the following command to uninstall it:
```text
sudo rmmod rtl8188fu
```

Once the driver program has been uninstalled, you can delete the configuration file for the driver program. The configuration file is usually located in the `/etc/modprobe.d/` directory.

Finally, you can reboot your computer to make sure that the driver program has been completely removed.
