### ISSUE TITLE
How to install on openwrt?

### ISSUE THREAD

**Issue by TimyIsCool** [1999AZZAR/use-RTL8188FTV-on-linux#6]
I am running a Pi with openwrt and I would like to use my usb wifi dongle with it for another network

**Comment by 1999AZZAR** [comment]
I don't have the specific knowledge on configuring a USB WiFi dongle with OpenWRT at the moment. It might be best to seek guidance from the OpenWRT community or explore relevant forums where experts can provide step-by-step instructions. Alternatively, you can patiently wait for someone with the necessary expertise to assist you. I'm sorry I can't provide a direct solution for this matter.
